#!/bin/sh -e

#for p in *.patch; do
#    patch -p1 < "$p"
#done

grep -lR "install -d -m 755" tools | xargs -n1 sed -i "s/install -d -m 755/install -m 755 -d/g"
sed -i "s/ln -fsn/ln -fs/g" arch/x86/Makefile

make
mkdir -p "$1/boot" "$1/usr/lib/modules"
make INSTALL_MOD_PATH="$1/usr" INSTALL_MOD_STRIP=1 modules_install
make INSTALL_PATH="$1/boot" install

make headers

# The headers require rsync for installation, this command
# simply does the equivalent using find, mkdir and cp.
find usr/include -name \*.h -type f | while read -r file; do
mkdir -p "$1/${file%/*}"
    cp -f "$file" "$1/$file"
done
