#!/bin/sh -e

meson build \
    --prefix=/usr \
    --sysconfdir=/etc \
    --buildtype=release \
    -Djson=disabled \
    -Ddefault_library=static \
    -Dnotify=disabled \
    -Ddocs=disabled \
    -Dtests=disabled

DESTDIR="$1" ninja -C build install
