#!/bin/sh -e
pkgname=xdpyinfo
pkgdir=$1
pkgver=$2
ls
./configure --prefix=/usr
make
make DESTDIR="${pkgdir}" install
install -m755 -d "${pkgdir}/usr/share/licenses/${pkgname}"
install -m644 COPYING "${pkgdir}/usr/share/licenses/${pkgname}/"
