#!/bin/sh -e

export DESTDIR="$1"

ls 3rdparty/glad
meson setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dvulkan=disabled \
    -Ddemos=false \
    output

ninja -C output
ninja -C output install
