#!/bin/sh -e
pkgname=python-soupsieve
pkgdir=$1
pkgver=$2
python setup.py build
python setup.py install --root="$pkgdir" --optimize=1

install -Dm644 LICENSE.md "$pkgdir"/usr/share/licenses/$pkgname/LICENSE.md
