#!/bin/sh -e

build_freetype() (
    cd freetype

    meson \
        --prefix=/usr \
        -Ddefault_library=both \
        -Dbzip2=disabled \
        -Dzlib=disabled \
        -Dpng=disabled \
        "$@" \
        . output

    ninja -C output
    DESTDIR="$1" ninja -C output install
)

build_harfbuzz() (
    cd harfbuzz

    meson \
        --prefix=/usr \
        -Dpkg_config_path="$1/usr/lib/pkgconfig" \
        -Ddefault_library=both \
        -Dglib=disabled \
        -Dfreetype=enabled \
        -Dgobject=disabled \
        -Dcairo=disabled \
        -Dicu=disabled \
        -Dbenchmark=disabled \
        -Dtests=disabled \
        . output

    ninja -C output
    DESTDIR="$1" ninja -C output install
)

# Point Freetype to the Harfbuzz files.
export CFLAGS="$CFLAGS -I$1/usr/include/harfbuzz"
export CFLAGS="$CFLAGS -L$1/usr/lib "
export PKG_CONFIG_PATH="$1/usr/lib/pkgconfig"

# Point Harfbuzz to the Freetype files.
export CXXFLAGS="$CXXFLAGS -I$1/usr/include/freetype2"
export CXXFLAGS="$CXXFLAGS -L$1/usr/lib"

set -x
build_freetype -Dharfbuzz=disabled
build_harfbuzz "$1"
build_freetype -Dharfbuzz=enabled --reconfigure
