#!/bin/sh -e

python setup.py build
python setup.py install --root="$1/" --optimize=1
install -Dm644 LICENSE "$1/usr/share/licenses/python-pillow/LICENSE"
install -dm755 "$1/usr/include/python3.9/"
install -m644 -t "$1/usr/include/python3.9/" src/libImaging/*.h
