#!/bin/sh -e

make
make DESTDIR="$1" ZICDIR=/usr/bin install

for continent in africa asia australasia europe northamerica southamerica; do
    ./zic -d "$1/usr/share/zoneinfo" "$continent"
    ./zic -d "$1/usr/share/zoneinfo/posix" "$continent"
    ./zic -d "$1/usr/share/zoneinfo/right" -L leapseconds "$continent"
done
./zic -d "$1/usr/share/zoneinfo" -p America/New_York
