#!/bin/sh -e

patch -p1 < rootless_modesetting.patch
patch -p1 < fix-crash.patch
sed -i "s/ModuleDuplicated\[\]/ModuleDuplicated[0]/" hw/xfree86/loader/loadmod.c
sed -i "s/defined(__GNUC__)/1/; s/__GNUC__/__TINYC__/" hw/xfree86/common/compiler.h hw/xfree86/vbe/vbe.h

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --disable-systemd-logind \
    --disable-xwayland \
    --disable-unit-tests \
    --enable-dri \
    --enable-dri2 \
    --enable-dri3 \
    --enable-glamor \
    --enable-glx \
    --disable-xwin \
    --enable-xorg \
    --enable-xvfb \
    --with-sha1=libcrypto \
    --with-systemd-daemon=off

make
make DESTDIR="$1" install
