#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-backtrace \
    --with-mujs \
    --without-idn \
    --disable-mouse \
    --disable-sysmouse \
    --disable-nls

make -j1
make DESTDIR="$1" install
