#!/bin/sh -e

./configure \
    --prefix=/usr \
    --sbindir=/usr/sbin \
    --enable-libipq \
    --with-xtlibdir=/lib/xtables \
    --disable-nftables

sed -i "s/install -pm/install -m/" -- **/*akefile

make
make DESTDIR="$1" install
