#!/bin/sh -e

sed -i "s/^XINIT/exec &/; s:tty_num=.*:tty_num=\${tty#/dev/tty}:g" startx.cpp
sed -i "s/.include <signal.h>/&\n#include <sys\/prctl.h>/; /main(/{N;s/.*/&\nprctl(PR_SET_CHILD_SUBREAPER);/}" xinit.c

# Make xauth optional at runtime.
cmd='command -v xauth >/dev/null \&\&'
sed "s#\(enable_xauth\)=1#$cmd&||\1=0#" startx.cpp > _
mv -f _ startx.cpp

./configure \
    --prefix=/usr \
    --with-xinitdir=/etc/X11/xinit

make
make DESTDIR="$1" install
