#!/bin/sh -e

sed -i "/pragma_deprecated/d" configure
export CFLAGS="$CFLAGS -DHAVE_PRAGMA_DEPRECATED=0 -DSDL_DISABLE_IMMINTRIN_H"

./configure \
    --cc="${CC:-cc}" \
    --cxx="${CXX:-c++}" \
    --prefix=/usr \
    --disable-debug \
    --disable-libxml2 \
    --enable-gpl \
    --enable-gnutls \
    --enable-libass \
    --enable-libdrm \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libx264 \
    --disable-libx265 \
    --enable-libxvid \
    --enable-shared \
    --enable-version3 \
    --enable-libv4l2 \
    --x86asmexe=nasm

make
make DESTDIR="$1" install

rm -rf "$1/usr/share/ffmpeg/examples"
