set expandtab
set hidden
set nocompatible
set noswapfile
set number
set ruler
set shiftwidth=4
set tabpagemax=100
set tabstop=4
imap jj <Esc>
nnoremap ff gT
nnoremap fg gt
noremap H ^
noremap L $
noremap j gj
noremap k gk
noremap gj j
noremap gk k
let g:tar_browseoptions="tf"
let g:tar_readoptions="Oxf"
