#!/bin/sh
# System wide environment and startup programs.

export PATH=/usr/bin

# Set default umask.
umask 022

# Load profiles from /etc/profile.d
for file in /etc/profile.d/*.sh; do
    [ -r "$file" ] && . "$file"
done
