#!/bin/sh -e
# Bumps the repo versions number of all packages in ${1:-$PWD}

updateVersion() {
    read -r version repoVer < $1/version
    if [ -n "$KISS_FORCE" ] || [ "$version" = git ] || grep -v files "$1/sources"; then
        echo $version $((repoVer+1)) > $1/version
    fi
}
if [ -z "$1" ]; then
    if [ -f version ]; then
        updateVersion .
    else
        for pkg in *; do
            if [ -d "$pkg" ]; then
                updateVersion $pkg
            fi
        done
    fi
else
    [ -d "$1" ]
    updateVersion $1
fi
