#!/bin/sh -e
# Show diff between top 2 sources of a given pkg

pkg="$1"
USE_LOCAL=0
if [ -z "$pkg" ] || [ "$pkg" = "." ]; then
    pkg=$(basename "$(pwd)")
    USE_LOCAL=1
    cd ..
elif [ -d "$pkg" ]; then
    USE_LOCAL=1
elif ! kiss s "$pkg" >> /dev/null; then
    echo "Invalid pgk $pkg"
    exit 1
fi

kiss s "$pkg" | grep -v "^/var/db/kiss/installed/" |  {
    if [ $USE_LOCAL -eq 0 ]; then
        read -r us
    else
        us=$pkg
    fi
    while read -r them ; do
        test "$them" -ef "$us" && continue
        diff ${DIFF_ARGS:--u} "$them" "$us" || true
        [ "${KISS_FORCE:-0}" -eq 1 ] || break
    done
}
