#!/bin/sh
# Show dependency tree for a given package

contains() {
    string="$1"
    substring="$2"
    [ "${string#*$substring}" != "$string" ]
}
export LIST=""
func() {
    if [ $1 -gt "${KISS_DEPTH:-1000}" ]; then
        return
    fi
    path=$(kiss search $2 |head -n1)
    for i in $(seq 1 $1); do
       printf "\t"
    done
    echo -n $2
    [ -z "$3" ] || echo -n " ($3)"
    [ -e $KISS_ROOT/var/db/kiss/installed/$2 ] && echo -n " (installed)"
    echo
    contains "$LIST" $2 && return;
    LIST="$LIST $2"
    if [ -f $path/depends ]; then
        for dep in $(cat $path/depends | cut -d" " -f 1); do
            func $(($1+1)) $dep
        done
    fi
}

func 0 $1
