#!/bin/sh -e
# Show dependency tree for a given package

contains() {
    string="$1"
    substring="$2"
    [ "${string#*$substring}" != "$string" ]
}
export LIST=""
func() {
    if [ $1 -gt "${KISS_DEPTH:-1000}" ]; then
        return
    fi
    path=$(kiss search $2 |head -n1)
    for _ in $(seq 1 $1); do
       printf "\t"
    done
    printf %s $2
    [ -z "$3" ] || printf %s " ($3)"
    [ -e $KISS_ROOT/var/db/kiss/installed/$2 ] && printf %s " (installed)"
    echo
    contains "$LIST" $2 && return;
    LIST="$LIST $2"
    if [ -f $path/depends ]; then
        while read -r dep _ ; do
            func $(($1+1)) $dep
        done < $path/depends
    fi
}

func 0 $1
