#!/bin/sh

install -D -t $1/usr/share/vim/ vimrc
install -D -t $1/etc/profile.d/ -- *.sh
install -D -t $1/etc/ ntp.conf
install -D -t $1/etc/myinit/init.d/ rc.local
install -D -t $1/etc/myinit/shutdown.d/ rc.shutdown

install -D -t $1/etc/modprobe.d/ blacklist.conf nobeep.conf
install -D -t $1/etc/ modules

