#!/bin/sh -e

# Setup base directories.
for d in boot dev efi etc home mnt usr var var/log var/empty opt run; do
    install -dm 755 "$1/$d"
done

MAIN_USER=${MAIN_USER:-arthur}

sed -i "s/MAIN_USER/$MAIN_USER/g" group passwd shadow

install -dm 555  "$1/proc"
install -dm 555  "$1/sys"
install -dm 1777 "$1/tmp"
install -dm 0750 "$1/root"
install -dm 0750 "$1/home/$MAIN_USER"
chown 1:1 "/home/$MAIN_USER"

# Setup /usr hierarchy.
for d in bin include lib share src; do
    install -dm 755 "$1/usr/$d"
done

# Setup manpages directories.
for d in 1 2 3 4 5 6 7 8; do
    install -dm 755 "$1/usr/share/man/man$d"
done

# Add symlinks.
ln -s usr/bin "$1/bin"
ln -s usr/bin "$1/sbin"
ln -s bin     "$1/usr/sbin"
ln -s usr/lib "$1/lib"
ln -s usr/lib "$1/lib64"
ln -s lib     "$1/usr/lib64"

install -dm 1777 "$1/var/tmp"
install -dm 1777 "$1/var/spool/mail"

ln -s spool/mail  "$1/var/mail"
ln -s ../run      "$1/var/run"
ln -s ../run/lock "$1/var/lock"

# /etc skeleton files.
for f in fstab group host.conf hosts issue \
         passwd profile securetty shells ; do
    install -m 644 "$f" "$1/etc"
done

for f in crypttab shadow; do
    install -m 600 "$f" "$1/etc"
done

ln -s /proc/self/mounts "$1/etc/mtab"
