#!/bin/sh -e

make \
    CC="${CC:-cc}" \
    SHARED=no \
    OPT="$CFLAGS -fPIC" \
    ZLIB=yes \
    PREFIX=/usr \
    SBINDIR=/usr/bin \
    SHAREDIR=/usr/share/hwdata

make DESTDIR="$1" install install-lib
