#!/bin/sh -e

# Upstream recently broke static linking. It is still supported via LDFLAGS but
# this disables output of the shared library. This sed call adds -all-static to
# the curl commands' compilation (keeping libraries in tact).
# See: https://github.com/curl/curl/issues/7475
sed -i 's/\(curl_LDADD =\)/\1 -all-static/' src/Makefile.in


./configure \
    --prefix=/usr \
    --disable-ares \
    --disable-ldap \
    --disable-manual \
    --enable-hidden-symbols \
    --enable-ipv6 \
    --enable-unix-sockets \
    --with-ca-fallback \
    --with-openssl \
    --with-pic \
    --without-icu \
    --without-libidn \
    --without-libidn2 \
    --without-libpsl \
    --without-librtmp

sed -i 's/link_static_flag=.*/link_static_flag=""/' libtool

make
make DESTDIR="$1" install
