#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"
./configure \
    --prefix=/usr \
    --enable-ipv6 \
    --enable-static \
    --disable-shared \
    --enable-unix-sockets \
    --disable-manual \
    --disable-ldap \
    --disable-ares \
    --with-openssl \
    --with-pic \
    --with-ca-fallback \
    --without-librtmp \
    --without-libpsl \
    --without-libidn2 \
    --without-brotli \
    --without-zstd

make
make DESTDIR="$1" install
