#!/bin/sh -e

export DESTDIR="$1"
for patch in *.patch; do
    patch -p1 <"$patch"
done

muon setup \
    -Dprefix=/usr \
    -Dmandir=/usr/share/man \
    -Dalsa=enabled \
    -Dlibmpv=true \
    -Dwayland=disabled \
    -Degl-x11=disabled \
    -Dx11=enabled \
    output

ninja -C output
muon  -C output install

rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion"
