#!/bin/sh -e

PERL_USE_UNSAFE_INC=1 \
PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor
make
make pure_install doc_install DESTDIR="$1"
find "$1" -name '.packlist' -exec rm {} +
find "$1" -name '*.pod' -exec rm {} +
