#!/bin/sh -e

for patch in *.patch; do
    patch -p1 < "$patch"
done

# Install terminfo to right location.
export TERMINFO="$1/usr/share/terminfo"
mkdir -p "$TERMINFO"

make
make PREFIX=/usr DESTDIR="$1" install
