#!/bin/sh -e

sed -i "/newterm/s/XK_Return/XK_T/" st-newterm*.diff
sed -i "s/shell/scroll/g" st-xresources*.diff
sed -i "s|static int oldbutton.*|static uint buttons; /* bit field of pressed buttons */|g" st-workingdir*.diff

for patch in *.diff *.patch ; do
    patch -p1 < "$patch"
done

# Install terminfo to right location.
export TERMINFO="$1/usr/share/terminfo"
mkdir -p "$TERMINFO"

make
make PREFIX=/usr DESTDIR="$1" install
