#!/bin/sh -e
install -D -t $1/bin kiss_hooks
install -D -t $1/etc/kiss_hooks.d/ *.sh
install -D -t $1/usr/share/kiss-hooks/ *.txt
mkdir $1/etc/profile.d
echo export KISS_HOOK=/bin/kiss_hooks > $1/etc/profile.d/kiss_hooks.sh
