#!/bin/sh -e

ls
install -D -t "$1/bin"               kiss_hooks
install -D -t "$1/etc/kiss_hooks.d/"  ./*.sh
install -D -t "$1/usr/share/kiss-compiler/" kiss_set_compiler.txt
install -D -t "$1/usr/share/kiss-conflict/" kiss_preferred.txt
mkdir "$1/etc/profile.d"
echo export KISS_HOOK=/bin/kiss_hooks > "$1/etc/profile.d/kiss_hooks.sh"
