#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC"

patch -p1 < pkcs7-fix.patch
patch -p1 < makefile_remove_extra_options.patch

make \
    prefix="$1/usr" \
    USE_SYSTEM_FREETYPE=yes \
    USE_SYSTEM_HARFBUZZ=yes \
    USE_SYSTEM_LIBJPEG=yes \
    USE_SYSTEM_ZLIB=yes \
    HAVE_GLUT=no \
    install
