#!/bin/sh -e

export CFLAGS="$CFLAGS"

patch -p1 < pkcs7-fix.patch
sed -i "s/-MMD -MP -o/-o/" Makefile
sed -i "s/,--gc-sections//" Makerules
sed -i "s/,-s//" Makerules

make \
    prefix="/usr" \
    DESTDIR="$1" \
    USE_SYSTEM_FREETYPE=yes \
    USE_SYSTEM_HARFBUZZ=yes \
    USE_SYSTEM_LIBJPEG=yes \
    USE_SYSTEM_ZLIB=yes \
    HAVE_GLUT=no \
    install
