#!/bin/sh -e
pkgname=vundle-git
pkgdir=$1
pkgver=$2

vimpath="${pkgdir}/usr/share/vim/vimfiles"
mkdir -p "${vimpath}/doc"
cp -R doc "${vimpath}"
mkdir -p "${vimpath}/autoload"
cp -R autoload "${vimpath}"

install -Dm 644 LICENSE-MIT.txt "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
install -Dm 644 README.md "${pkgdir}/usr/share/doc/${pkgname}/README"
