#!/bin/sh -e
pkgname=autorandr
pkgdir=$1
pkgver=$2
make DESTDIR="${pkgdir}" PREFIX=/usr install
# zsh completion
install -vDm 644 "contrib/zsh_completion/_${pkgname}" \
-t "${pkgdir}/usr/share/zsh/site-functions/"
# docs
install -vDm 644 README.md -t "${pkgdir}/usr/share/doc/${pkgname}/"
