#!/bin/sh -e

# Uncomment if using valgrind or similar.
# :>nostrip

./configure \
    --prefix=/usr \
    --syslibdir=/usr/lib \
# Uncomment if using valgrind or similar.
#   --enable-debug

make
sed -i "s/typedef \w* wchar_t/typedef __WCHAR_TYPE__ wchar_t/g; s/typedef unsigned wint_t/typedef __WINT_TYPE__ wint_t/g" ./obj/include/bits/alltypes.h;
make DESTDIR="$1" install

mkdir -p "$1/usr/bin"
ln -s  /usr/lib/ld-musl-x86_64.so.1 "$1/usr/bin/ldd"

# Fix incorrect symlink to libc.so.
ln -sf libc.so "$1/usr/lib/ld-musl-x86_64.so.1"

# Install BSD compatibility headers.
install -Dm 755 cdefs.h "$1/usr/include/sys/cdefs.h"
install -Dm 755 queue.h "$1/usr/include/sys/queue.h"
install -Dm 755 tree.h  "$1/usr/include/sys/tree.h"

# Install getconf.
cc getconf.c -o "$1/usr/bin/getconf"
cc getent.c  -o "$1/usr/bin/getent"
